{
 "title": "Topic Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": "SELECT DISTINCT tname FROM current_topics"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Publishers",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT * FROM current_topics\r\nWHERE tname = 'machine_state_P14SONB058' and direction = 'publisher'",
     "rawQueryText": "SELECT * FROM current_topics\r\nWHERE tname = '$topic' and direction = 'publisher'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current Subscribers",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "queryText": "SELECT * FROM current_topics\r\nWHERE tname = '$topic' and direction = 'subscriber'",
     "rawQueryText": "SELECT * FROM current_topics\r\nWHERE tname = '$topic' and direction = 'subscriber'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "# Subscribers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT time_stamp, \n       connections_loc,\n       connections_ext\nFROM topics\nWHERE tname = 'machine_state_P14SONB058' \n  AND direction = 'publisher'\nGROUP BY time_stamp\n",
     "rawQueryText": "SELECT time_stamp, \n       connections_loc,\n       connections_ext\nFROM topics\nWHERE tname = '$topic' \n  AND direction = 'publisher'\nGROUP BY time_stamp\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Message Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT time_stamp, \n       sum(message_drops)\nFROM topics\nWHERE tname = 'machine_state_P14SONB058' \n  AND direction = 'subscriber'\nGROUP BY time_stamp\n",
     "rawQueryText": "SELECT time_stamp, \n       sum(message_drops)\nFROM topics\nWHERE tname = '$topic' \n  AND direction = 'subscriber'\nGROUP BY time_stamp\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Topic Write",
   "type": "timeseries",
   "description": "todo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT time_stamp, \n       dfreq,\n       tsize\nFROM topics\nWHERE tname = 'machine_state_P14SONB058' \n  AND direction = 'publisher'\nGROUP BY time_stamp\n",
     "rawQueryText": "SELECT time_stamp, \n       dfreq,\n       tsize\nFROM topics\nWHERE tname = '$topic' \n  AND direction = 'publisher'\nGROUP BY time_stamp\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Topic Read",
   "type": "timeseries",
   "description": "todo",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT time_stamp, \n       dfreq,\n       tsize\nFROM topics\nWHERE tname = 'machine_state_P14SONB058' \n  AND direction = 'publisher'\nGROUP BY time_stamp\n",
     "rawQueryText": "SELECT time_stamp, \n       dfreq,\n       tsize\nFROM topics\nWHERE tname = '$topic' \n  AND direction = 'publisher'\nGROUP BY time_stamp\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}