{
 "title": "Topic Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": "SELECT DISTINCT tname FROM topics"
   }
  ]
 },
 "panels": [
  {
   "title": "Publishers for Topic \"$topic\"",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT * FROM current_topics\r\nWHERE tname = 'machine_state_P14SONB058' and direction = 'publisher'",
     "rawQueryText": "SELECT * FROM current_topics\r\nWHERE tname = '$topic' and direction = 'publisher'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Subscribers for Topic \"$topic\"",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "queryText": "SELECT * FROM current_topics\r\nWHERE tname = '$topic' and direction = 'subscriber'",
     "rawQueryText": "SELECT * FROM current_topics\r\nWHERE tname = '$topic' and direction = 'subscriber'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "# Subscribers to Topic \"$topic\"",
   "type": "timeseries",
   "description": "Show the number of subscribers to a topic over the time, grouped by local/external host.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT time_stamp, \n       connections_loc,\n       connections_ext\nFROM topics\nWHERE tname = '$topic' \n  AND direction = 'publisher'\nGROUP BY time_stamp\n",
     "rawQueryText": "SELECT time_stamp, \n       connections_loc,\n       connections_ext\nFROM topics\nWHERE tname = '$topic' \n  AND direction = 'publisher'\nGROUP BY time_stamp\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Message Drops",
   "type": "timeseries",
   "description": "Sum of the message drops across all subscribers of a selected topic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT time_stamp, \n       sum(message_drops)\nFROM topics\nWHERE tname = 'machine_state_P14SONB058' \n  AND direction = 'subscriber'\nGROUP BY time_stamp\n",
     "rawQueryText": "SELECT time_stamp, \n       sum(message_drops)\nFROM topics\nWHERE tname = '$topic' \n  AND direction = 'subscriber'\nGROUP BY time_stamp\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Published Data for Topic \"$topic\"",
   "type": "timeseries",
   "description": "Show the published data from all publishers of the selected topic over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT time_stamp, \n       SUM(dfreq * tsize) AS total_write\nFROM topics\nWHERE tname = '$topic' \n  AND direction = 'publisher'\nGROUP BY time_stamp;\n\n",
     "rawQueryText": "SELECT time_stamp, \n       SUM(dfreq * tsize) AS total_write\nFROM topics\nWHERE tname = '$topic' \n  AND direction = 'publisher'\nGROUP BY time_stamp;\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Received Data for Topic \"$topic\"",
   "type": "timeseries",
   "description": "Show the received data across all subscribers of the selected topic over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT time_stamp, \n       SUM(dfreq * tsize) AS total_read\nFROM topics\nWHERE tname = '$topic' \n  AND direction = 'subscriber'  \nGROUP BY time_stamp;\n",
     "rawQueryText": "SELECT time_stamp, \n       SUM(dfreq * tsize) AS total_read\nFROM topics\nWHERE tname = '$topic' \n  AND direction = 'subscriber'  \nGROUP BY time_stamp;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}