{
 "title": "Host Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hname",
    "label": "hname",
    "query": "SELECT DISTINCT hname FROM processes"
   },
   {
    "name": "pid",
    "query": "SELECT DISTINCT pid FROM current_processes WHERE hname='$hname' "
   }
  ]
 },
 "panels": [
  { "title": "Host Overview ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk Usage $hname",
   "type": "gauge",
   "description": "For each host show the percentage of used disk space.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n  hname, \n  (capacity_disk - available_disk) * 100.0 / capacity_disk AS disk_usage_percent\nFROM \n  hosts\nWHERE \n  hname = '${hname}'  \nORDER BY \n  time_stamp DESC \nLIMIT 1\n",
     "rawQueryText": "SELECT \n  hname, \n  (capacity_disk - available_disk) * 100.0 / capacity_disk AS disk_usage_percent\nFROM \n  hosts\nWHERE \n  hname = '${hname}'  \nORDER BY \n  time_stamp DESC \nLIMIT 1\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "RAM Usage $hname",
   "type": "gauge",
   "description": "For each host show the percentage of used memory.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n  hname, (total_memory - available_memory) * 100.0 / total_memory AS memory_used\nFROM \n  hosts\nWHERE \n  hname = '$hname' \nORDER BY \n  time_stamp DESC \nLIMIT 1\n",
     "rawQueryText": "SELECT \n  hname, (total_memory - available_memory) * 100.0 / total_memory AS memory_used\nFROM \n  hosts\nWHERE \n  hname = '$hname' \nORDER BY \n  time_stamp DESC \nLIMIT 1\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CPU Usage $hname",
   "type": "gauge",
   "description": "For each host show how much CPU is used (new monitoring param needed)",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT hname, cpu_load\nFROM hosts\nWHERE hname = 'P14SONB058' \nAND time_stamp = (SELECT MAX(time_stamp) FROM hosts WHERE hname = 'P14SONB058')\n\n\n",
     "rawQueryText": "SELECT hname, cpu_load\nFROM hosts\nWHERE hname = '$hname' \nAND time_stamp = (SELECT MAX(time_stamp) FROM hosts WHERE hname = '$hname')\n\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Host over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage over Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "queryText": "SELECT \n  time_stamp, \n  (capacity_disk - available_disk) * 100.0 / capacity_disk AS disk_usage_percent\nFROM \n  hosts\nWHERE \n  hname = 'P14SONB058'",
       "rawQueryText": "SELECT \n  time_stamp, \n  (capacity_disk - available_disk) * 100.0 / capacity_disk AS disk_usage_percent\nFROM \n  hosts\nWHERE \n  hname = '${hname}'",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "RAM Usage over Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "queryText": "SELECT \n  time_stamp, (total_memory - available_memory) * 100.0 / total_memory AS memory_used\nFROM \n  hosts\nWHERE \n  hname = 'P14SONB058'",
       "rawQueryText": "SELECT \n  time_stamp, (total_memory - available_memory) * 100.0 / total_memory AS memory_used\nFROM \n  hosts\nWHERE \n  hname = '$hname'",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "CPU Usage over Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "queryText": "SELECT cpu_load, time_stamp from hosts where hname = '$hname'",
       "rawQueryText": "SELECT cpu_load, time_stamp from hosts where hname = '$hname'",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes on Host $hname ",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "queryText": "SELECT * FROM current_processes",
       "rawQueryText": "SELECT * FROM current_processes",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Process Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load of Process $pid (pid)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
     "targets": [
      {
       "queryText": "SELECT \n    time_stamp, \n    hname, \n    cpu_load \nFROM \n    process_performance\nWHERE pid = '$pid' and hname ='$hname'\n",
       "rawQueryText": "SELECT \n    time_stamp, \n    hname, \n    cpu_load \nFROM \n    process_performance\nWHERE pid = '$pid' and hname ='$hname'\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "CPU Times of Process $pid (pid)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
     "targets": [
      {
       "queryText": "SELECT \n    time_stamp, \n    hname, \n    cpu_kernel_time, \n    cpu_user_time\nFROM \n    process_performance\nWHERE pid = '18968' and hname ='P14SONB058'",
       "rawQueryText": "SELECT \n    time_stamp, \n    hname, \n    cpu_kernel_time, \n    cpu_user_time\nFROM \n    process_performance\nWHERE pid = '$pid' and hname ='$hname'",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Working Set Size of Process $pid (pid)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
     "targets": [
      {
       "queryText": "SELECT \n    time_stamp, \n    hname, \n    current_working_set_size, \n    peak_working_set_size\nFROM \n    process_performance\nWHERE pid = '18968' and hname ='P14SONB058'",
       "rawQueryText": "SELECT \n    time_stamp, \n    hname, \n    current_working_set_size, \n    peak_working_set_size\nFROM \n    process_performance\nWHERE pid = '$pid' and hname ='$hname'",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  }
 ]
}